#Задача 1

In [ ]:
import numpy as np

a = np.matrix([[1, 2, 1], [-2, 1, 1]])
b = np.matrix([[3, 1], [-1, 0], [2, 4]])
c = np.matrix([[-2, 2], [1, -1], [1, 2]])
# Умножаем матрицу b на 2
two_b = 2 * b

# Транспонируем матрицу a, чтобы её размерность стала 2x3
a_transposed = a.T

# Выполняем операцию транспонированной a и 2b
result = a_transposed + two_b

print("\n a + 2b:")
print(result)

# Умножаем матрицу c на 2
two_c = 2 * c

# Выполняем операцию b + 2c
result = b + two_c

print("\n b + 2c:")
print(result)



 a + 2b:
[[7 0]
 [0 1]
 [5 9]]

 b + 2c:
[[-1  5]
 [ 1 -2]
 [ 4  8]]


#Задача 2

In [ ]:
# Создаем матрицу 8x8, заполненную нулями
matrix = np.zeros((8, 8), dtype=int)
print('пустая матрица')
print(matrix)

# Заполняем шахматную доску (чередуем 1 и 0)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print('\n шахматная матрица')
print(matrix)


пустая матрица
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

 шахматная матрица
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Задача 3

In [ ]:
import numpy as np

# Создаем первый вектор длиной 15 элементов
first_vector = np.arange(0, 1.5, 0.1)

# Создаем второй вектор длиной 6 элементов
second_vector = np.arange(1, 7)

# Преобразуем первый вектор в матрицу 5x3
matrix1 = first_vector.reshape(5, 3)

# Преобразуем второй вектор в матрицу 3x2
matrix2 = second_vector.reshape(3, 2)

# Выполняем перемножение матриц
result = np.dot(matrix1, matrix2)

print("Первая матрица (5x3):")
print(matrix1)

print("\nВторая матрица (3x2):")
print(matrix2)

print("\nРезультат перемножения матриц:")
print(result)


Первая матрица (5x3):
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]

Вторая матрица (3x2):
[[1 2]
 [3 4]
 [5 6]]

Результат перемножения матриц:
[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


#Задача 4

In [ ]:
import numpy as np

# Создаем вектор размерностью 36 с четными целыми значениями, начиная с 1
vector = np.arange(1, 73, 2, dtype=np.int32)

# Выделяем элементы, значения которых кратны 3
result_vector = vector[vector % 3 == 0]

print("Исходный вектор:")
print(vector)

print("\nЭлементы, кратные 3:")
print(result_vector)


Исходный вектор:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]

Элементы, кратные 3:
[ 3  9 15 21 27 33 39 45 51 57 63 69]
